### ISSUE TITLE
一个建议

### ISSUE THREAD

**Issue by woshinibb66** [wxy1343/freemyv2rayssr#2]
把账号密码全部保存到本地以后，希望开发一个全部登陆然后购买公益套餐的脚本，这样一键全部购买，一直买够三十天后邀请就不会注销了，而普通的大概三天过后就会注销，自己邀请也会被扣除，虽然可以没有多少时间就可以刷出来，也只是建议，另外作者有捐赠的渠道吗，ouo

**Comment by wxy1343** [comment]
感谢建议，已经更新了

**Comment by wxy1343** [comment]
![image](https://user-images.githubusercontent.com/49909001/106928681-65534c80-674e-11eb-8147-7eb01fb7a767.png)
感谢支持
