### ISSUE TITLE
完全不会弄😂代码小白，只会主程序填个邀请码，以为那个可以像软件一样可以导出文本。然后可以购买还是谢谢了，

### ISSUE THREAD

**Issue by woshinibb66** [wxy1343/freemyv2rayssr#3]
只会主程序填个邀请码，以为那个可以像软件一样可以导出文本。然后可以购买还是谢谢了，

**Comment by woshinibb66** [comment]
下载了py不会玩

**Comment by wxy1343** [comment]
[已经打包好了](https://github.com/wxy1343/freemyv2rayssr/releases/tag/2)
