### ISSUE TITLE
ubuntu下运行提示“验证超时”

### ISSUE THREAD

**Issue by DarkNight710** [wxy1343/freemyv2rayssr#5]
打包文件win下运行没问题，但是register.py在ubuntu下运行，过不了验证，提示“验证超时”导致“注册失败”。
目录下似乎没有得到缺口图片和完整图片，不知道问题出在哪，求指教，谢谢！

**Comment by wxy1343** [comment]
你调试看看，卡在那一步了

**Comment by DarkNight710** [comment]
> 你调试看看，卡在那一步了

终于调好了！机器上没有图形chrome所以取消了headless注释，然后以为前面的注释也需要取消，然后就一直卡着了。

这个网站登录好像也加了滑块验证，期待更新（我自己也用注册的方法试试，不知道能不能成功）
